language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm-nightly

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer self-update
  - composer install --no-interaction --prefer-source
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - if [[ "$TRAVIS_PHP_VERSION" != *"nightly" ]]; then phpenv config-rm xdebug.ini; fi;
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
